name: build and deploy homepage
on:
  push:
    paths:
      - homepage/**
      - .github/workflows/homepage.yaml
  workflow_dispatch:
permissions:
  contents: read
  id-token: write
  pages: write
jobs:
  react-app-to-github-pages:
    uses: MichaelDiers/github-workflows/.github/workflows/react-app-to-github-pages.yaml@main
    with:
      add-build-info: true
      working-directory: homepage
